name: 'Freshlinks'
description: 'Validate local markdown links in a repository'
author: 'Reid Draper'
inputs:
  glob:
    required: true
    description: 'Glob to find markdown files'
  suggestions:
    required: false
    description: 'Provide link suggestions when an invalid link is found'
  error-template:
    required: false
    description: 'A mustache template string to override error messages. See the README for more detailed information.'
  absolute-base-url:
    required: false
    description: 'Production url of code. When passed, markdown files using this URL will error with instructions to make it relative instead.'
  absolute-base-path:
    required: false
    description: 'If a url is https://thehub.github.com/epd/planning and it lives in docs/epd/planning.md this value should be "docs"'
runs:
  using: 'node12'
  main: 'freshlinks-action/dist/index.js'
