name: 'Freshlinks'
description: 'Validate local markdown links in a repository'
author: 'Reid Draper'
inputs:
  glob: # change this
    required: true
    description: 'Glob to find markdown files'
  suggestions:
    required: false
    description: 'Provide link suggestions when an invalid link is found'
runs:
  using: 'node12'
  main: 'freshlinks-action/dist/index.js'
