name: 'Freshlinks'
description: 'Validate local markdown links in a repository'
author: 'Reid Draper'
inputs:
  glob: # change this
    required: true
    description: 'glob to find markdown files'
runs:
  using: 'node12'
  main: 'freshlinks-action/dist/index.js'
